name: flutter_webapi_first_course
description: //

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  uuid: ^3.0.6
  google: ^0.0.1
  google_fonts: ^4.0.3
  http: ^0.13.5
  http_interceptor: ^1.0.2
  logger: ^1.2.2
  flutter_slidable: ^2.0.0
  intl: ^0.18.0
  path_provider: ^2.0.13
  envify: ^2.0.3
  sqflite: ^2.2.5
  path: ^1.8.2
  flutter_launcher_icons: ^0.12.0
  quickalert: ^1.0.1
  shrink_sidemenu: ^2.0.0+2-null-safety
  shared_preferences: ^2.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/ico.png"

flutter:

  uses-material-design: true
